# Generated by Django 4.2 on 2024-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizsubmission',
            name='answers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
