# Generated by Django 4.2 on 2024-10-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_studentquizsubmission_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquizsubmission',
            name='answers',
        ),
    ]
